CLASS zcl_po_item_top DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    TYPES: tt_data TYPE STANDARD TABLE OF ztb_d_po_item WITH EMPTY KEY.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_PO_ITEM_TOP IMPLEMENTATION.
ENDCLASS.
